import {
  Activity,
  ArchiveX,
  Boxes,
  Braces,
  Clock3,
  Cloud,
  Copy,
  Cpu,
  Database,
  Gauge,
  GitBranch,
  Globe2,
  HardDrive,
  Inbox,
  Layers3,
  type LucideIcon,
  Network,
  PackageOpen,
  Radio,
  RadioTower,
  Scaling,
  Search,
  ServerCog,
  Shield,
  Waves,
} from "lucide-react"

export const nodeTypeIcons: Record<string, LucideIcon> = {
  "event.source": Radio,
  "http.endpoint": Globe2,
  "function.service": Braces,
  "router.condition": GitBranch,
  "redis.cache": Database,
  "rabbitmq.queue": Inbox,
  worker: Cpu,
  database: HardDrive,
  "websocket.gateway": RadioTower,
  "external.api": Cloud,
  "scheduler.cron": Clock3,
  "logger.metrics": Activity,
  "network.load-balancer": Network,
  "resilience.rate-limiter": Gauge,
  "resilience.circuit-breaker": Shield,
  "stream.kafka-topic": Layers3,
  "storage.object": PackageOpen,
  "network.cdn": Network,
  "data.search-engine": Search,
  "compute.batch-processor": Boxes,
  "data.database-proxy": ServerCog,
  "data.read-replica": Copy,
  "messaging.dead-letter-queue": ArchiveX,
  "stream.processor": Waves,
  "control.autoscaler": Scaling,
}

export const fallbackNodeIcon: LucideIcon = Braces
